version: '3.1'

services:

  app:
    image: wordpress:latest
    container_name: g2bc
    restart: always
    ports:
      - 80:80
    volumes:
      - ./public_html/wp-content:/var/www/html/wp-content
      - ./wp_data:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}:3306'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
    depends_on:
      - db
    networks:
      - internal

  db:
    container_name: '${WORDPRESS_DB_HOST}'
    image: mysql:8.0
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./g2bcun_geral:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    expose:
      - 3306
      - 33060
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '3000:80'
    environment:
      PMA_HOST: '${WORDPRESS_DB_HOST}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}' 
    depends_on:
      - db
    networks:
      - internal

networks:
  internal:
    external: true

volumes:
  wp_data:
  db:
