version: '3.1'

services:

  app:
    image: wordpress:latest
    container_name: g2bc
    restart: always
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
    ports:
      - 8001:80
    volumes:
      - ./public_html:/var/www/html
    depends_on:
      - db
    networks:
      - internal

  db:
    container_name: '${WORDPRESS_DB_HOST}'
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db:/var/lib/mysql
      - ./g2bcun_geral:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - internal

networks:
  internal:
    external: true

volumes:
  public_html:
  db:
