version: '3.1'

services:

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
    volumes:
      - ./public_html:/var/www/html

  db:
    container_name: '${WORDPRESS_DB_HOST}'
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db:/var/lib/mysql
      - ./g2bcun_geral:/docker-entrypoint-initdb.d

volumes:
  wordpress:
  db: